name = "Avalon"
uuid = "d462d321-1585-4840-9f3e-06f5c1b6ea25"
authors = ["Andrei Zhabinski <andrei.zhabinski@gmail.com>"]
version = "0.2.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLDataUtils = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NNlibCUDA = "a00861dc-f156-4864-bf3c-e6376f28a68d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Yota = "cd998857-8626-517d-b929-70ad188a48f0"

[compat]
CUDA = "3"
CUDAKernels = "0.3.1"
ChainRules = "1"
ChainRulesCore = "1"
Distributions = "0.25"
KernelAbstractions = "0.7"
LoopVectorization = "0.12"
MLDataUtils = "0.5"
NNlib = "0.7"
NNlibCUDA = "0.1.9"
Tullio = "0.3"
Yota = "0.6.2"
julia = "1.6"
